# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# Sample workflow for building and deploying a Jekyll site to GitHub Pages
name: Deploy Jekyll site
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '3.0'
      - run: gem install bundler && bundle install
      - run: bundle exec jekyll build
      - uses: actions/upload-artifact@v2
        with:
          name: site
          path: _site/
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: site
          path: _site/
      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: _site
